#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EmployeeManager.Resource", IsApplication=true)]

namespace EmployeeManager
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int rotate_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in_down = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_in_right = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_in_up = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int slide_out_down = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int slide_out_right = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int slide_out_up = 2130968582;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int m_white = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int my_green = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int my_light_blue = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int my_red = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int _add_employee_form = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int _employee_panel = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int _input_add_employee = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int add_btn = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int delete_btn = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int edit_btn = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int save_btn = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int search_btn = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int select_color_btn = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080010
			public const int InfoEmployeeContainer = 2131230736;
			
			// aapt resource value: 0x7f080000
			public const int actionBar = 2131230720;
			
			// aapt resource value: 0x7f080015
			public const int btnAddEmployee = 2131230741;
			
			// aapt resource value: 0x7f08000d
			public const int btnDeleteEmployee = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int btnEditEmployee = 2131230734;
			
			// aapt resource value: 0x7f080002
			public const int btnSaveEmployee = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int btnSelectColor = 2131230724;
			
			// aapt resource value: 0x7f08000c
			public const int categoryName = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int createOrEditEmployee = 2131230721;
			
			// aapt resource value: 0x7f080011
			public const int employeeInfoName = 2131230737;
			
			// aapt resource value: 0x7f08001a
			public const int employeeName = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int employeeOccupation = 2131230747;
			
			// aapt resource value: 0x7f080005
			public const int inputEmployeeBirthday = 2131230725;
			
			// aapt resource value: 0x7f08000b
			public const int inputEmployeeEmail = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int inputEmployeeHireDate = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int inputEmployeeName = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int inputEmployeeOccupation = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int inputEmployeePhone = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int inputEmployeeSalary = 2131230728;
			
			// aapt resource value: 0x7f080019
			public const int linearLayout1 = 2131230745;
			
			// aapt resource value: 0x7f080013
			public const int linearLayout2 = 2131230739;
			
			// aapt resource value: 0x7f080017
			public const int listEmployees = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int logoName = 2131230744;
			
			// aapt resource value: 0x7f080016
			public const int noEmployeeInList = 2131230742;
			
			// aapt resource value: 0x7f08000f
			public const int scrollView1 = 2131230735;
			
			// aapt resource value: 0x7f080014
			public const int searchEmployee = 2131230740;
			
			// aapt resource value: 0x7f080009
			public const int textView1 = 2131230729;
			
			// aapt resource value: 0x7f080012
			public const int textView2 = 2131230738;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddEmployeeForm = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EmployeeInfo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int rowEmployee = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int create_employee = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int edit_employee = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int employee_birthday_hint = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int employee_email_hint = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int employee_hiredate_hint = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int employee_name_hint = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int employee_occupation_hint = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int employee_phone_hint = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int employee_salary_hint = 2131099655;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int CustomLightTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
